TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "PLAYER_ID"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''

SELECT
    MAX(CLIENT_TIME) AS "LAST_SEEN",
    DATA_CENTER_ID AS "SILO",
    REALM,
    USER_ID AS "DEVICE_ID",
    PLATFORM,
    FED_ID,
    ABOUT_ID AS "PL_ID",
    INGAME_NICKNAME_ACTIVE AS "NAME",
    ALL_ID,
    MAX(PROGRESS_INDEX01) AS "THRONE_LEVEL",
    MAX(PLAYER_POWER),
    MAX(SOFT_CURRENCY1_BALANCE) AS "GOLD_BALANCE",
    MAX(SOFT_CURRENCY2_BALANCE) AS "MOONDUST_BALANCE"
    
FROM
    "ELEPHANT_DB"."AOV"."PLAYER_CONNECTION_REPORT"

WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND PL_ID = '{filter_value}'
    
GROUP BY
    SILO,
    REALM,
    DEVICE_ID,
    PLATFORM,
    FED_ID,
    PL_ID,
    NAME,
    ALL_ID

ORDER BY
    LAST_SEEN DESC
    
LIMIT 10000
;
'''
