TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''

SELECT
    DATE(SERVER_TIME) AS "DATE",
    SERVER_TIME AS "TIME",
    FED_ID,
    PROGRESS_INDEX AS "LEVEL",
    USER_ID AS "DEVICE_ID",
    PLATFORM,
    TRANSACTION_ID,
    ORIGINAL_CONTENT_ID,
    QUANTITY_PROMO_PERCENTAGE,
    TO_NUMBER(PRICE_PAID,38,2) AS "PRICE",
    CONTENT_CURRENCY_CODE AS "_CURRENCY",
    TO_NUMBER(REVENUE_EUR,38,2) AS "REV_EUR",
    HARD_CURRENCY_EARNED,
    HARD_CURRENCY_BALANCE,
    COUNT(TRANSACTION_ID) OVER (PARTITION BY FED_ID) AS "TOTAL_TR_S",
    SUM(TO_NUMBER(PRICE_PAID,38,2)) OVER (PARTITION BY FED_ID) AS "TOTAL_AMOUNT_PAID",
    SUM(TO_NUMBER(REVENUE_EUR,38,2)) OVER (PARTITION BY FED_ID) AS "TOTAL_REV_EUR",
    SUM(HARD_CURRENCY_EARNED) OVER (PARTITION BY FED_ID) AS "TOTAL_HARD_CURRENCY_EARNED"
FROM "ELEPHANT_DB"."AOV"."IAP"
WHERE
    SERVER_TIME >= '{st_date}'
    AND SERVER_TIME < '{end_date}'
    AND FED_ID = '{account}'

GROUP BY
    DATE,
    TIME,
    FED_ID,
    LEVEL,
    DEVICE_ID,
    PLATFORM,
    VERSION,
    COUNTRY,
    TRANSACTION_ID,
    ORIGINAL_CONTENT_ID,
    QUANTITY_PROMO_PERCENTAGE,
    HARD_CURRENCY_EARNED,
    HARD_CURRENCY_BALANCE,
    PRICE,
    REV_EUR,
    _CURRENCY
ORDER BY
    TIME DESC
LIMIT 10000
;
'''