TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "HERO NAME"
SILO = "NO"
REALM = "NO"
DATE = "NO"

SQL_REQ =   '''

SELECT
    DATE(CLIENT_TIME) AS "DATE",
    CLIENT_TIME AS "TIME",
    REALM,
    USER_ID AS "DEVICE",
    FED_ID AS "FED",
    PROGRESS_INDEX01 AS "PLAYER_LEVEL",
    ITEM_NAME AS "HERO",
    PROGRESS_INT AS "ACTION",
    ITEM_LEVEL AS "HERO_LEVEL",
    STAR_LEVEL AS "STARS"
FROM
    "ELEPHANT_DB"."AOV"."PROGRESSION"
WHERE
    SERVER_TIME >= '2021-01-01'
    AND SERVER_TIME < '2025-01-01'
    AND FED_ID = '{account}'
    AND HERO LIKE '%{filter_value}'
ORDER BY 
    TIME ASC,
    HERO ASC
LIMIT
    10000
;
'''
