TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''

SELECT DIStinCT
    DATE(T_GS.CLIENT_TIME) AS "DATE",
    T_GS.CLIENT_TIME AS "TIME",
    DATA_CENTER_ID AS "SIKO",
    T_GS.EVENT_DATA:realm::INT AS "REALM",
    T_GS.FED_ID AS "FED",
    T_GS.EVENT_DATA:coord::STRING AS "COORD",
    T_EL_2.NAME AS "PURPOSE",
    T_EL.NAME AS "ACTION_NAME",
    T_EL_3.NAME AS "ITEM_NAME",
    (T_GS.EVENT_DATA:shield_duration::INT/60)::INT AS "SHIELD_DURATION"

FROM
    "TRACKING_DB"."AOV"."GAMESERVERS" AS T_GS
    
LEFT JOIN
    "ELEPHANT_DB"."DIMENSIONS"."EVENT" AS T_EV
    ON (T_GS.EVENT_ID = T_EV.EVENT_ID)
LEFT JOIN
    "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_EL
        ON (T_GS.EVENT_DATA:base_int::INT = T_EL.ID)
LEFT JOIN
    "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_EL_2
        ON (T_GS.EVENT_DATA:base_int_purpose::INT = T_EL_2.ID)
LEFT JOIN
    "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_EL_3
        ON (T_GS.EVENT_DATA:item_name::INT = T_EL_3.ID)

WHERE
    T_GS.CLIENT_TIME >= '{st_date}'
    AND T_GS.CLIENT_TIME < '{end_date}'
    AND T_GS.FED_ID = '{account}'
    AND T_GS.EVENT_ID = 406652
    AND T_GS.EVENT_DATA:base_int::INT IN (406656, 406657, 406658)

ORDER BY
    TIME ASC

LIMIT 10000
;

'''