TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''

SELECT
    DATE(CLIENT_TIME) AS "DATE",
    CLIENT_TIME AS "TIME",
    FED_ID AS "FED",
    REALM,
    SPEND_ACTION AS "SPENT_FOR",
    ITEM_NAME AS "LOTTERY_TYPE",
    ITEM_DATA AS "TICKET_TYPE",
    CURRENCY01 AS "TICKET_NAME",
    CURRENCY01_SPENT::INT AS "TICKETS_SPENT",
    CURRENCY01_BALANCE::INT AS "TICKET_BALANCE"
    
FROM
    "ELEPHANT_DB"."AOV"."CURRENCY_SPENT"

WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND FED_ID = '{account}'
    AND SPEND_ACTION = 'Lottery'
    
ORDER BY 
    TIME

LIMIT
    10000
;
'''