TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "ITEM NAME"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''

SELECT
    DATE(T_GS.CLIENT_TIME) AS "DATE",
    T_EL.NAME AS "ITEM_NAME",
    T_EV.EVENT_NAME AS "EVENT_NAME",
    COUNT(T_EV.EVENT_NAME) AS "ACTIONS",
    MIN(T_GS.CLIENT_TIME) AS "_FROM",
    MAX(T_GS.CLIENT_TIME) AS "_TO"

FROM
    "TRACKING_DB"."AOV"."GAMESERVERS" AS T_GS
    
LEFT JOIN
    "ELEPHANT_DB"."DIMENSIONS"."EVENT" AS T_EV
    ON (T_GS.EVENT_ID = T_EV.EVENT_ID)

LEFT JOIN
    "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_EL
    ON (T_GS.EVENT_DATA:item_name::INT = T_EL.ID)

WHERE
    SERVER_TIME >= '{st_date}'
    AND SERVER_TIME < '{end_date}'
    AND FED_ID = '{account}'
    AND EVENT_DATA:item_name::INT <> 0
    AND EVENT_DATA:item_name::INT IS NOT NULL
    AND LOWER(ITEM_NAME) LIKE LOWER('%{filter_value}%')

GROUP BY
    DATE,
    EVENT_NAME,
    ITEM_NAME
    
ORDER BY
    _FROM ASC
LIMIT 10000
;
'''