TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''

SELECT
    DATE(CLIENT_TIME) AS "DATE",
    REALM,
    FED_ID,
    PROGRESS_INDEX01 AS "THRONE_LEVEL",
    RESOURCE_INT AS "RECIEVED_FROM",
    ITEM_NAME,
    ITEM_LEVEL,
    SUM(ITEM_EARNED) AS "TOTAL_EARNED",
    SUM(ITEM_LOST) AS "TOTAL_LOST"
    
FROM
    "ELEPHANT_DB"."AOV"."RESOURCES_REWARDS"

WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND FED_ID = '{account}'

GROUP BY
    DATE,
    REALM,
    FED_ID,
    THRONE_LEVEL,
    RECIEVED_FROM,
    EVENT_ACTOR,
    ITEM_NAME,
    ITEM_LEVEL
    
ORDER BY
    DATE ASC,
    RECIEVED_FROM ASC,
    ITEM_NAME ASC

LIMIT
    10000
;
'''