TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''

WITH T_CON AS
(
  SELECT
    FED_ID,
    REALM,
    INGAME_NICKNAME_ACTIVE AS "NAME",
    MAX(PROGRESS_INDEX01) AS "LEVEL"
  FROM "ELEPHANT_DB"."AOV"."PLAYER_CONNECTION_REPORT"
  WHERE
    SERVER_TIME >= '{st_date}'
    AND SERVER_TIME < '{end_date}'
  GROUP BY
    FED_ID,
    REALM,
    NAME
)

SELECT
    T_GOLD.DATA_CENTER_ID AS "SILO",
    T_CON.REALM AS "REALM",
    T_GOLD.COUNTRY AS "COUNTRY",
    T_CON.FED_ID AS "FED",
    T_CON.NAME AS "NAME",
    T_CON.LEVEL AS "LEVEL",
    T_GOLD.EVENT_DATA:action_id::STRING AS "CAMPAIGN",
    T_GOLD.EVENT_DATA:reward_name::STRING AS "REWARD",
    SUM(T_GOLD.EVENT_DATA:reward_amount::INT) AS "TOTAL_QNTY"
FROM 
    "TRACKING_DB"."AOV"."GOLD" AS T_GOLD
LEFT JOIN
    T_CON ON (T_GOLD.FED_ID = T_CON.FED_ID)
WHERE
    T_GOLD.SERVER_TIME >= '{st_date}'
    AND T_GOLD.SERVER_TIME < '{end_date}'
    AND T_GOLD.EVENT_ID = 51855
    
GROUP BY 1,2,3,4,5,6,7,8
ORDER BY
    TOTAL_QNTY DESC,
    FED ASC, 
    REWARD ASC
LIMIT 100000
;
'''
