TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''
SELECT
    DATE(CLIENT_TIME) AS "DATE",
    DATA_CENTER_ID AS "SILO",
    REALM,
    USER_ID AS "DEVICE_ID",
    PLATFORM,
    ABOUT_ID AS "PL_ID",
    FED_ID,
    INGAME_NICKNAME_ACTIVE AS "NAME",
    ALL_ID,
    MAX(PROGRESS_INDEX01) AS "THRONE_LEVEL",
    MAX(PLAYER_POWER),
    MAX(SOFT_CURRENCY1_BALANCE) AS "GOLD_BALANCE",
    MAX(SOFT_CURRENCY2_BALANCE) AS "MOONDUST_BALANCE",
    T_IAP.TRANSACTIONS,
    T_IAP.REVENUE_EUR

FROM
    "ELEPHANT_DB"."AOV"."PLAYER_CONNECTION_REPORT" AS T_PL

LEFT JOIN
    (SELECT
        FED_ID AS FED,
        COUNT(DISTINCT TRANSACTION_ID) AS "TRANSACTIONS",
        SUM(REVENUE_EUR::INT) AS "REVENUE_EUR"
    FROM
        "ELEPHANT_DB"."AOV"."IAP"
    WHERE
        FED = '11f5d0d2-3712-11ec-8969-46f86c1f51d3'
    GROUP BY
        FED) AS T_IAP

ON (FED = T_PL.FED_ID)

WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND FED_ID = '{account}'

GROUP BY
    DATE,
    SILO,
    REALM,
    DEVICE_ID,
    PLATFORM,
    FED_ID,
    PL_ID,
    NAME,
    ALL_ID,
    TRANSACTIONS,
    REVENUE_EUR

ORDER BY
    DATE DESC

LIMIT 10000
;
'''
