TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "NO"
SILO = "YES"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''
SELECT
    DATE(CLIENT_TIME) AS "DATE",
    YEAR(CLIENT_TIME) AS "YEAR",
    MONTH(CLIENT_TIME) AS "MONTH",
    WEEK(CLIENT_TIME) AS "WEEK",
    DATA_CENTER_ID AS "SILO",
    EVENT_REALM_AGE,
    CRITERIA_ACTOR AS "E_TYPE",
    EVENT_NAME AS "E_NAME",
    COUNT(DISTINCT FED_ID) AS "PARTICIPANTS"
FROM
    "ELEPHANT_DB"."MOE"."SCORE_INTERACTION"
WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND SILO LIKE '{silo}'
    AND E_TYPE <> 'NULL'
    AND SCORE_INT = 'Score Points Earned'
GROUP BY
    DATE,
    YEAR,
    MONTH,
    WEEK,
    EVENT_REALM_AGE,
    SILO,
    E_TYPE,
    E_NAME
ORDER BY 
    DATE ASC, 
    SILO ASC,
    E_TYPE ASC
LIMIT 10000
;
'''